spring:
  jpa:
    hibernate:
      ddl-auto: update
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://rabbitnode1:3307/blog
    password: suyimoqi1117*
    username: blog
    driver-class-name: com.mysql.jdbc.Driver