view:
  maxPagenation: 5
  perPageSize: 10
  articlesSortBy: createAt
file:
  upload:
    tempLocation: \fileupload\image
spring:
  datasource:
    url: jdbc:mysql://rabbitnode1:3307/blog?useSSL=false&characterEncoding=utf-8
    password: suyimoqi1117*
    username: blog
    driver-class-name: com.mysql.jdbc.Driver